# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [71]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [72]:
chipo=pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv',sep='\t')

### Step 4. See the first 10 entries

In [73]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [74]:
len(chipo)

4622

In [75]:
chipo.shape[0]

4622

### Step 6. What is the number of columns in the dataset?

In [76]:
#len(chipo.columns)
chipo.shape[1]

5

### Step 7. Print the name of all the columns.

In [77]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

### Step 8. How is the dataset indexed?

In [78]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [79]:
chipo["item_name"].value_counts().head(1)

item_name
Chicken Bowl    726
Name: count, dtype: int64

### Step 10. For the most-ordered item, how many items were ordered?

In [80]:
chipo.groupby("item_name")["quantity"].sum().max()

761

### Step 11. What was the most ordered item in the choice_description column?

In [81]:
chipo["choice_description"].value_counts().head(1)

choice_description
[Diet Coke]    134
Name: count, dtype: int64

### Step 12. How many items were orderd in total?

In [82]:
print(chipo['quantity'].sum())

4972

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

In [83]:
chipo["item_price"]=chipo['item_price'].str.split('$').str[1]
chipo["item_price"]=chipo["item_price"].astype(float)
chipo["item_price"]

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

#### Step 13.b. Create a lambda function and change the type of item price

In [84]:
chipo["item_price"].fillna(0,inplace=True)   #NaN değerler olduu için integera çeviremiyorduk
chipo['item_price'] = chipo['item_price'].apply(lambda x: int(x))

#### Step 13.c. Check the item price type

In [85]:
chipo["item_price"].dtype

dtype('int64')

### Step 14. How much was the revenue for the period in the dataset?

In [90]:
revenue = (chipo['item_price'] * chipo['quantity']).sum()
print(revenue)

36616

### Step 15. How many orders were made in the period?

In [91]:
chipo["order_id"].nunique()

1834

### Step 16. What is the average revenue amount per order?

In [92]:
# Solution 1
round(chipo.groupby("order_id")["item_price"].sum().mean(), 2)

np.float64(17.48)

In [99]:
# Solution 2
total_revenue = chipo['item_price'].sum()
unique_orders = chipo['order_id'].nunique()
total_revenue / unique_orders

np.float64(17.476553980370774)

### Step 17. How many different items are sold?

In [95]:
chipo['item_name'].nunique()

50